# Generated by Django 3.2.18 on 2023-02-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('available_seats', models.PositiveSmallIntegerField(default=4)),
                ('comments', models.TextField(blank=True)),
                ('departure_location', models.CharField(max_length=140)),
                ('departure_date', models.DateTimeField()),
                ('arrival_location', models.CharField(max_length=140)),
                ('arrival_date', models.DateTimeField()),
                ('rating', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false when the ride is already done.', verbose_name='active status')),
                ('is_offered', models.BooleanField(default=False, help_text='Set to true when the ride is offered.', verbose_name='offered status')),
                ('offered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offered_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.circle')),
                ('passengers', models.ManyToManyField(related_name='passengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-departure_date', '-arrival_date'],
                'unique_together': {('offered_by', 'departure_date', 'arrival_date')},
            },
        ),
    ]
